services:
  - type: web
    name: ai-news-dashboard
    env: docker
    plan: free

    envVars:
      - key: GROQ_API_KEY
        sync: false

    disk:
      name: db-storage
      mountPath: /data
      sizeGB: 1

    healthCheckPath: /health
